project_id = "owgiskzmtmfurnwnfgsi"

[functions.generate-snapshots]
verify_jwt = false

[functions.parse-cv]
verify_jwt = false

[functions.ingest-jobs]
verify_jwt = false

[functions.geocode-snapshots]
verify_jwt = false
